spring: 
 profiles: 
  active: 
   - dev

---
spring: 
 profiles: dev
 application: 
  name: microservice-config-ycx-dev

---   
spring: 
 profiles: test
 application: 
  name: microservice-config-ycx-test